---
title: "RWorksheet_Animas#3b"
author: "Marvin Anthony Y. Animas"
date: "2024-10-03"
output: pdf_document
---

```{r}

#1 Create the data frame

#a Write the codes.
df <- data.frame(
Respondents = 1:20,
Sex = c(2, 2, 1, 2, 2, 2, 2, 2, 2, 2, 1, 2, 2, 2, 2, 2, 2, 2, 1, 2),
Fathers_Occupation = c(1, 3, 3, 3, 1, 2, 3,1,1,1,3,2,1,3,3,1,3,1,2,1),
Persons_At_Home = c(5,7,3,8,5,9,6,7,8,4,7,5,4,7,8,8,3,11,7,6),
Siblings_At_School = c(6,4,4,1,2,1,5,3,1,2,3,2,5,5,2,1,2,5,3,2),
Types_Of_Houses = c(1, 2, 3, 1, 1, 3, 3, 1, 2, 3, 2, 3, 2, 2, 3, 3, 3, 3, 3, 2))
df

#b. Describe the data. Get the structure or the summary of the data
#The data surveys a total of 20 respondents,it shows data like sex, Fathers occupation, Persons at home,Siblings at school and types of houses,the data gathers informations of the respondents.

#c. Is the mean number of siblings attending is 5?
mean_of_siblings<-mean(df[,5])
mean_of_siblings
#The mean number of siblings is not 5 the mean number is 2.95

#d. Extract the 1st two rows and then all the columns using the subsetting functions. Write the codes and its output.
first_two<-df[1:2,]
first_two

#e. Extract 3rd and 5th row with 2nd and 4th column. Write the codes and its result.
Third_Fifth<-df[c(3,5), c(2,4)]
Third_Fifth

#f. Select the variable types of houses then store the vector that results as types_houses. Write the codes.
Types_Houses<-df[,6]
Types_Houses

#g. Select only all Males respondent that their father occupation was farmer. Write the codes and its output.
Males<-subset(df, df[,2] == 1 & df[,3] == 1 )
Males

#h. Select only all females respondent that have greater than or equal to 5 number of siblings attending school. Write the codes and its outputs.
Female<- subset(df, df[,2] == 2 & df[,5] >= 5)
Female
```
```{r}
#2. Write a R program to create an empty data frame. Using the following codes:

#df = data.frame(Ints=integer(), Doubles=double(), Characters=character(), Logicals=logical(), Factors=factor(),stringsAsFactors=FALSE) print("Structure of the empty dataframe:") print(str(df))

#a. Describe the results.
df = data.frame(Ints=integer(),
Doubles=double(), Characters=character(),
Logicals=logical(),
Factors=factor(),
stringsAsFactors=FALSE)
print("Structure of the empty dataframe:")
print(str(df))

#The code shows an empty data frame named df in R with 5 variables (Ints, Doubles, Characters, Logicals and Factors) and 0 observations.


```
```{r}
#3. Create a .csv file of this. Save it as HouseholdData.csv
respondents <- c(1, 2, 3, 4, 5, 6, 7, 8, 9, 10)
sex <- c("Male", "Female", "Female", "Male", "Male", "Female", "Female", "Male", "Female", "Male")
father <- c(1, 2, 3, 3, 1, 2, 2, 3, 1, 3)
persons <- c(5, 7, 3, 8, 6, 4, 4, 2, 11, 6)
siblings <- c(2, 3, 0, 5, 2, 3, 1, 2, 6, 2)
houses <- c("Wood", "Congrete", "Congrete", "Wood", "Semi-congrete", "Semi-congrete", "Wood", "Semi-congrete", "Semi-congrete", "Congrete")

HOUSEdata <- data.frame(Respondents = respondents, Sex = sex, Fathers_Occupation = father, Persons_at_Home = persons, Siblings_at_School = siblings, Types_of_Houses = houses)
HOUSEdata

write.csv(HOUSEdata, file = "HouseholdData.csv", FALSE)

#a.Import the csv file into the R environment. Write the codes.
 Imported <- read.csv("HouseholdData.csv")
 Imported
 
#b.Convert the Sex into factor using factor() function and change it into integer.[Legend:Male = 1 and Female = 2]. Write the R codes and its output.
Imported$Sex <- factor(Imported$Sex, levels = c("Male", "Female"), labels = c(1, 2))
Imported


#c. Convert the Type of Houses into factor and change it into integer. [Legend: Wood= 1; Concrete = 2; Semi-Concrete = 3]. Write the R codes and its output.

Imported$Types_of_Houses <- factor(Imported$Types_of_Houses, levels = c("Wood", "Congrete", "Semi-congrete"), labels = c(1, 2, 3))
Imported

 
#d. On father’s occupation, factor it as Farmer = 1; Driver = 2; and Others = 3. What is the R code and its output?
Imported$Fathers_Occupation <- factor(Imported$Fathers_Occupation, levels = c("Farmer", "Driver", "Others"), labels = c(1, 2, 3))
Imported

#e.Select only all females respondent that has a father whose occupation is driver. Write the codes and its output.
Female_Drivers <- subset(Imported, Sex == 2 & Fathers_Occupation == 2)
Female_Drivers
 
#f.Select the respondents that have greater than or equal to 5 number of siblings attending school. Write the codes and its output.
Siblings_Up5 <- subset(Imported, Siblings_at_School >= 5)
Siblings_Up5


#4 Interpret the graph.
#This graph displays the sentiment analysis of tweets over several days in July 2020.
#It shows the count of tweets categorized as negative, neutral, and positive for each day.
#The highest peak for negative sentiment occurs on July 15th.There are relative peaks for Positive comments on July 15th and July 21st.
```