---
title: "RWorksheet_2Animas#2"
author: "Marvin Anthony Y. Animas"
date: "2024-09-28"
output: html_document
---
#1. Create a vector using : operator

#a. Sequence from -5 to 5. Write the R code and its output.Describe its output.
vector1 <- -5:5
vector1
#The Output begins from -5 to +5 by 1.

#b. x <- 1:7. What will be the value of x?
x <- 1:7
x
#The Value of X is 1 2 3 4 5 6 7

#2.* Create a vector using seq() function

#a. seq(1, 3, by=0.2) # specify step size Write the R script and its output. Describe the output.
vector2<-c(seq(1, 3, by=0.2))
vector2
#The output displays a sequence from 1 to 3 by 0.2.

#3. 
ages<- c(34, 28, 22, 36, 27, 18, 52, 39, 42, 29, 35, 31, 27,22, 37, 34, 19, 20, 57, 49, 50, 37, 46, 25, 17, 37, 43, 53, 41, 51, 35,24,33, 41, 53, 40, 18, 44, 38, 41, 48, 27, 39, 19, 30, 61, 54, 58, 26,18.)
ages

#a. Access 3rd element, what is the value?
ages[3]

#b. Access 2nd and 4th element, what are the values?
ages[c(2,4)]

#c. Access all but the 4th and 12th element is not included. Write the R script and its output.
ages[-c(4, 12)]

#4. *Create a vector x <- c("first"=3, "second"=0, "third"=9). Then named the vector, names(x).
names <- c("first"=3, "second"=0, "third"=9)

#a. Print the results. Then access x[c("first", "third")]. Describe the output.
names[c("first", "third")]

#5. Create a sequence x from -3:2.
X<-seq(from = -3, to = 2)
X


#a. Modify 2nd element and change it to 0;
  X[2] <- 0
  X
  
#The output changed the 2nd element from -2 becomes 0.


#6

#a. Create a data frame for month, price per liter (php) and purchase-quantity (liter). Write the R scripts and its output.

fueltable<-data.frame(
  Month = c("Jan", "Feb", "March", "Apr", "May", "June"),
  LiterPrice = c(52.50, 57.25, 60.00, 65.00, 74.25, 54.00),
  QuantityPurchased = c(25, 30, 40, 50, 10, 45)
  )
fueltable

#b. What is the average fuel expenditure of Mr. Cruz from Jan to June? Note: Use ‘weighted.mean(liter,purchase)‘. Write the R scripts and its output.

AverageF<- weighted.mean(fueltable$LiterPrice, fueltable$QuantityPurchased)
AverageF
#The Average is 59.2625

#7. R has actually lots of built-in datasets. For example, the rivers data “gives the lengths (in miles) of 141 “major” rivers in North America, as compiled by the US Geological Survey”.
rivers

#a. Type “rivers” in your R console. Create a vector data with 7 elements, containing the number of elements (length)in rivers, their sum (sum), mean (mean),median(median), variance(var), standard deviation(sd),minimum (min) and maximum (max).

data <- c(length(rivers), sum(rivers), mean(rivers), median(rivers), var(rivers),
sd(rivers), min(rivers), max(rivers))
data

#b. What are the results?
#The results are [1]    141.0000  83357.0000    591.1844    425.0000 243908.4086    493.8708 [7]    135.0000   3710.0000

#c. Write the R scripts and its outputs.
data <- c(length(rivers), sum(rivers), mean(rivers), median(rivers), var(rivers),
sd(rivers), min(rivers), max(rivers))
data

#8

#a. Create vectors according to the above table.Write the R scripts and its output.

PowerRanking <- c(1:25)

CelebrityName <- c("Tom Cruise", "Rolling Stones", "Ophrah Winfrey", "U2", "Tiger Woods", "Steven Spielberg", "Howard Stern", "50 Cent", "Cast of the Sopranos", "Dan Brown", "Bruce Springsteen", "Donald Trump", "Muhammad Ali", "Paul McCartney", "George Lucas", "Elton John", "David Letterman", "Phil Mickelson", "J.K Rowling", "Bradd Pitt", "Peter Jackson", "Dr. Phil McGraw", "Jay Lenon", "Celine Dion", "Kobe Bryant")

Pay <- c(67, 90, 225, 110, 90, 332, 302, 41, 52, 88, 55, 44, 55, 40, 233, 34, 40, 47, 75, 25, 39, 45, 32, 40, 31)

ForbesRanking <- data.frame(PowerRanking = PowerRanking,
CelebrityName = CelebrityName, Pay = Pay)
ForbesRanking

#b. Modify the power ranking and pay of J.K. Rowling. Change power ranking to 15 and pay to 90. Write the R scripts and its output.

ForbesRanking[ForbesRanking$CelebrityName == "J.K Rowling", "PowerRanking"] <-15
ForbesRanking[ForbesRanking$CelebrityName == "J.K Rowling", "Pay"] <- 90

ForbesRanking


#c. Create an excel file from the table above and save it as csv file(PowerRanking). Import the csv file into the RStudio. What is the R script?
write.csv(ForbesRanking, file = "PowerRanking.csv", row.names = FALSE)
importedRanking <- read.csv("PowerRanking.csv")
importedRanking

#D.Access the rows 10 to 20 and save it as Ranks.RData. Write the R script and its output.
  Ranking <- ForbesRanking[10:20, ]
  save(Ranking, file = "Ranks.RData")
  Ranking
  
#e. Describe its output.
#The output displays only rank 10 to 20.

#9. Download the Hotels-Vienna https://tinyurl.com/Hotels-Vienna


# a. Import the excel file into your RStudio. What is the R script?
Hotels_Vienna <- read_excel("hotels-vienna.xlsx")
Hotels_Vienna

#b How many dimensions does the dataset have? What is the R script? WHat is its output?
Dimensions <- dim(Hotels_Vienna)
Dimensions
#Its output connsist of 428 and 24

#c.Select columns country, neighbourhood,price, stars, accomodation_type, and ratings. Write the R script.
SelectedColumns <- Hotels_Vienna[, c("country", "neighbourhood", "price", "stars", "accommodation_type",     "rating")]
print(head(SelectedColumns))

#d.Save the data as **new.RData to your RStudio. Write theR script.
save(SelectedColumns, file = "new.RData")
SelectedColumns
  
#e. Display the first six rows and last six rows of the new.RData. What is the R script?
load("new.RData")
head(SelectedColumns)
tail(SelectedColumns)

#10. Create a list of ten (10) vegetables you ate during your lifetime. If none, just list down.
Vegetables<- list("Malunggay", "Carrots", "Pechay", "Monggo", "Tomato", "Green Peas", "EggPlant", "Garlic", "Onion", "Corn")
Vegetables

#b.Add 2 additional vegetables after the last vegetablesin the list. What is the R script and its output?
Vegetables <- append(Vegetables, c("Cabbage", "Mushroom"))
Vegetables
  
#c. Add 4 additional vegetables after index 5. How many datapoints does your vegetable list have? What is the R script and its output?
Vegetables<- append(Vegetables, c("Ginger", "Broccoli","Cauliflower","Celery"), after = 5)
Vegetables
length(Vegetables)

#d. Remove the vegetables in index 5, 10, and 15. How many vegetables were left? Write the codes and its Output.
Vegetables <- Vegetables[-c(5, 10, 15)]
Vegetables
length(Vegetables)
